# This workflow runs the Bigtable Conformance Test suite against the Bigtable
# client library.
# See https://github.com/googleapis/cloud-bigtable-clients-test
name: manual_conformance
on:
  workflow_dispatch:

jobs:
  bigtable_conformance_manual:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [
          '3.0',
          '3.1',
          '3.2',
          '3.3',
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: googleapis/cloud-bigtable-clients-test
          ref: main
          path: cloud-bigtable-clients-test
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.20.2'
      - run: .kokoro/conformance.sh
